name: pull_request_func_postgresql
on:
  pull_request:
env:
  GO_VERSION: 1.12.15
  CI_GOMAXPROCS: 0
  INSOLAR_LOG_LEVEL: warn
  GOPATH: ${{github.workspace}}/go
jobs:
  test-func-pgsql:
    runs-on: self-hosted
    name: test-func-pgsql
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/insolar
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: test_func
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
        env:
          POSTGRES_ENABLE: 1
        run: |
          make build
          make functest
